### ISSUE TITLE
Can it work with an Imager transformed image url?

### ISSUE THREAD

**Issue by mark-chief** [clearbold/fixmealink#3]
I am trying the below:
```
{% set image = entry.seatImage.one() %}
{% set transformedImage = craft.imager.transformImage(image, { width: 1800, ratio: 16/9, format: 'jpg' }) %}
<img src="{{ transformedImage|obfuscateAssetUrl }}"/>
```

And getting this error:
`Trying to get property 'url' of non-object`

Craft: 3.4.24
Plugin 1.0.1

THANKS

**Comment by heymarkreeves** [comment]
I think it should, but you wouldn't be able to pass it the asset. It's been a while since I worked on this—I'm looking at the README. If you can't pass an asset directly to `obfuscateAssetUrl`, you can pass any URL to `obfuscate`:

```
<a href="{{ entry.url|obfuscate }}"
```

So in your case you would pass `{{transformedImage.getUrl()|obfuscate}}`.

Does that work?

**Comment by mark-chief** [comment]
Thanks for getting back to me, I saw that but noticed it will take you to the source URL once clicked, and doesn't expire like ``|obfuscateAssetUrl`` does.

**Comment by heymarkreeves** [comment]
Right...because the purpose of the plugin was to keep people from sharing links to proprietary PDFs. So you'd have to be logged in and viewing the site to click on and read a PDF. If you copied its URL and shared it, no one else could use that link after 15 minutes.

I'm curious what the use case is there for a transformed image. Is that something you're making available for a time-restricted download? Or embedding in your site?

I'm seeing that Imager supports transforms on a URL, too. Have you tried doing an Imager transform on an obfuscated URL? From their docs:

```
{% set externalImage = 'http://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/pia19808-main_tight_crop-monday.jpg' %}

{% set transformedImages = craft.imager.transformImage(externalImage, [
    { width: 600, height: 600 },
    { width: 500, height: 500 },
    { width: 400, height: 400 }
    ]) %}
```

**Comment by mark-chief** [comment]
Or even if it could work with a Craft Asset transform that would surface. Understand its probably not top of your priorities though! 

I get the same error with a craft asset transform and:
```
{% set image = entry.seatImage.one() %}
{% set transformedImage = image.getUrl('seatView') %}
{{ transformedImage|obfuscateAssetUrl }}
```

**Comment by heymarkreeves** [comment]
I think the issue here is going to be that your browser has to read that transformed image URL and display it. How can you mask an image URL without a redirect to the original resource?

A .htaccess 301 redirect on an image URL embedded in a web page will show the image at the redirect destination, right? Wouldn't the same work here if you obfuscate the transformed URL?

**Comment by mark-chief** [comment]
OK, thanks for your help, I get it probably wasn't intended for this use case where I needed to try and prevent an image being shared on social media. I wanted the image URL to expire at 15 mins.

**Comment by heymarkreeves** [comment]
There is a way to do that! :) Years ago we had a situation where someone was hot linking our CSS for their site. We used .htaccess to redirect the background image url to something that made it clear they had stolen our code :)

Here you go https://gist.github.com/circa1977/005b2e9a4039bcc2cd44

**Comment by heymarkreeves** [comment]
You could probably figure out how to configure that so it worked for all images at a particular URL route. You're using .htaccess to deny access to images on your site unless they're embedded in a page at your domain.

**Comment by mark-chief** [comment]
Lol, thats a good idea.

Cheers, You’ve put me in the right direction i think! Didn’t think of htaccess
